bind(name = "android/crosstool", actual = "@android_ndk//:toolchain-libcpp")

android_sdk_repository(
    name="androidsdk",
    path="/Users/gar/android/sdk",
    # Feb 2018::: latest api supported is 25
    # api_level=25,	   # Oreo, 8.0.0, required for java.nio.file.*
    api_level=26,	   # Oreo, 8.0.0, required for java.nio.file.*
    # default uses latest build tools installed
    # build_tools_version="27.0.3"
)

android_ndk_repository(
    name="androidndk",
    # Feb 2018: latest NDK version supported is 14:
    path="/Users/gar/android/android-ndk-r14b",
    # future:
    #path="/Users/gar/android/sdk/ndk-bundle",
    # Feb 2018::: latest api supported is 25
    api_level=25,
)

local_repository(
	name = "openocf_java",
	path = "/Users/gar/openocfj/src",
)

# bug workaround: openocfj/src/BUILD cannot use its own WORKSPACE so we
# must add a local repo for the openocf repo:
local_repository(
	name = "openocf",
	path = "/Users/gar/openocf",
)

