android_library(
    name = "common",
    srcs = glob(["org/openocf/test/*.java"]),
    deps = ["@openocf_java//:openocf_japi"],
    visibility = ["//android/server/java:__pkg__",
                  "//android/client/java:__pkg__"]
)
