android_library(
    name = "common",
    srcs = glob(["org/openocf/test/*.java"]),
    deps = ["//:openocf_japi"],
    visibility = ["//demos/android/server/java:__pkg__",
                  "//demos/android/client/java:__pkg__"]
)
