# iotivity-java

Java API/SDK for Iotivity

This is the Java API and JNI wrapper code for Iotivity, broken out
into a stand-alone project.  It is derived from work by Petre Eftime
(https://gerrit.iotivity.org/gerrit/#/c/7895/[patch 7895]).

It seems to build and work on Ubuntu with the latest source pulled
from master.  It also works with
https://github.com/iotk/iochibity[iochibity] on Darwin.

=== building

==== jni

Step one is to adapt `source.me` to your system. The provided code
assumes that this SDK is cloned to `$HOME/iotivity/kit/java` and that
the Iotivity dev kit is at `$HOME/iotivity/iotivity`; change as
needed, then source it: `$ source source.me`.

Then build the JNI layer. Edit `jni/Makefile` to adjust the vars to
your setup, then just run `$ make <host>`, for example `make linux`.

NOTE: If you build it on the Edison, you want ARCH=x86; on 64 bit
Ubuntu, make it x86_64.

WARNING: The makefile is very much a Work-In-Progress. The goal is to
make it like the one for Lua, which is very portable, but it needs
some work.

==== api

To build the Java API:

[source,sh]
----
$ cd api
$ mvn install
----

The `mvn` command will compile the Java source, package it in a jar
file, and install it to your local repository.  The result should be in

[source,sh]
----
$HOME/.m2/repository/iotivity/iotivity-api/1.1.0-SNAPSHOT
----

Note that this version number is for the Java API; it is not the
version number of the Iotivity library.

==== examples

Only one of the original Android samples has been ported; it's in `examples/minimal`.

To build it, just run `$ mvn package`.  Note that you do not need to install it.

To run it, do `$ ./bin/<host>/<role>`, for example, `$ ./bin/linux/jserver`.

If you get errors pertaining to linkage, check the `source.me` paths
and the paths in the `bin/<host>/<role>` code.

On Darwin you may have to run the `fixlinks.sh` script to fixup the linkage info.

=== related

See also https://github.com/iotk/iotivity-clj[iotk/iotivity-clj],
which is a Clojure SDK for Iotivity, built on this Java SDK.

For assistance, try https://iotivity-slack.herokuapp.com/[iotivity-slack].


== merging master

* Until OCProvisioningManager.h has been renamed in master, all
  #include refs to this in header files must be edited to
  OCProvisioningManager.hpp

* Use OC_UNUSED to eliminate warnings

in JniOcPlatform.cpp, restore
#define UNUSED(expr) (void)(expr);


* JniOcPlatform.cpp:
-    OCDeviceInfo deviceInfo = {
-	deviceName : NULL,
-	types : NULL,
-  	specVersion : NULL
-        // dataModelVersions : NULL
-    };
-


The master codebase includes Android-dependent code.  This repository
is Java only, so merging master to this involves some tweaking.

* JniCaInterface.[ch] compiles, but it's for Android only - remove it?

* fix #ifdef __ANDROID__ code, e.g. in JniOcStack.h, etc.

* switch from android/log.h to logger.h, e.g. in JniOcStack.h
i.e. restore:
#ifdef __ANDROID__
 #include <android/log.h>
#else
#include "logger.h"
#endif

restore:
-#ifdef __ANDROID__
 #define LOGI(...) __android_log_print(ANDROID_LOG_INFO, TAG, __VA_ARGS__)
 #define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, TAG, __VA_ARGS__)
 #define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)
-#else
-#define LOGI(...) OIC_LOG_V(INFO, TAG, __VA_ARGS__)
-#define LOGD(...) OIC_LOG_V(DEBUG, TAG, __VA_ARGS__)
-#define LOGE(...) OIC_LOG_V(ERROR, TAG, __VA_ARGS__)
-#endif


* there are some casts that must be made explicit, e.g. in JniOcStack.h
restore
-            if (g_jvm->AttachCurrentThread( (void**)&env, nullptr) < 0)
for
+            if (g_jvm->AttachCurrentThread(&env, nullptr) < 0)
