java_library(
    name = "common",
    srcs = glob(["org/openocf/test/*.java"]),
    #deps = ["@openocf_java//:openocf_japi"],
    deps = ["//:openocf_japi"],
    visibility = ["//demos/stdjava/Server:__pkg__",
                  "//demos/stdjava/Client:__pkg__"]
)
