java_library(
    name = "common",
    srcs = glob(["org/openocf/test/*.java"]),
    deps = ["@openocf_java//:openocf_japi"],
    visibility = ["//stdjava/Server:__pkg__",
                  "//stdjava/Client:__pkg__"]
)
