/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_exceptions_OCFNotImplementedException */

#ifndef _Included_org_iochibity_exceptions_OCFNotImplementedException
#define _Included_org_iochibity_exceptions_OCFNotImplementedException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_exceptions_OCFNotImplementedException_serialVersionUID
#define org_iochibity_exceptions_OCFNotImplementedException_serialVersionUID -3042686055658047285LL
#undef org_iochibity_exceptions_OCFNotImplementedException_serialVersionUID
#define org_iochibity_exceptions_OCFNotImplementedException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
