/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_PropertyForResource */

#ifndef _Included_org_iochibity_PropertyForResource
#define _Included_org_iochibity_PropertyForResource
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
