/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_MsgNotificationIn */

#ifndef _Included_org_iochibity_MsgNotificationIn
#define _Included_org_iochibity_MsgNotificationIn
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_MsgNotificationIn_INVALID
#define org_iochibity_MsgNotificationIn_INVALID 0L
#undef org_iochibity_MsgNotificationIn_DISCOVERY
#define org_iochibity_MsgNotificationIn_DISCOVERY 1L
#undef org_iochibity_MsgNotificationIn_DEVICE
#define org_iochibity_MsgNotificationIn_DEVICE 2L
#undef org_iochibity_MsgNotificationIn_PLATFORM
#define org_iochibity_MsgNotificationIn_PLATFORM 3L
#undef org_iochibity_MsgNotificationIn_REPRESENTATION
#define org_iochibity_MsgNotificationIn_REPRESENTATION 4L
#undef org_iochibity_MsgNotificationIn_SECURITY
#define org_iochibity_MsgNotificationIn_SECURITY 5L
#undef org_iochibity_MsgNotificationIn_PRESENCE
#define org_iochibity_MsgNotificationIn_PRESENCE 6L
#undef org_iochibity_MsgNotificationIn_RD
#define org_iochibity_MsgNotificationIn_RD 7L
#undef org_iochibity_MsgNotificationIn_NOTIFICATION
#define org_iochibity_MsgNotificationIn_NOTIFICATION 8L
#ifdef __cplusplus
}
#endif
#endif
