/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_IMessage */

#ifndef _Included_org_iochibity_IMessage
#define _Included_org_iochibity_IMessage
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_IMessage_INVALID
#define org_iochibity_IMessage_INVALID 0L
#undef org_iochibity_IMessage_DISCOVERY
#define org_iochibity_IMessage_DISCOVERY 1L
#undef org_iochibity_IMessage_DEVICE
#define org_iochibity_IMessage_DEVICE 2L
#undef org_iochibity_IMessage_PLATFORM
#define org_iochibity_IMessage_PLATFORM 3L
#undef org_iochibity_IMessage_REPRESENTATION
#define org_iochibity_IMessage_REPRESENTATION 4L
#undef org_iochibity_IMessage_SECURITY
#define org_iochibity_IMessage_SECURITY 5L
#undef org_iochibity_IMessage_PRESENCE
#define org_iochibity_IMessage_PRESENCE 6L
#undef org_iochibity_IMessage_RD
#define org_iochibity_IMessage_RD 7L
#undef org_iochibity_IMessage_NOTIFICATION
#define org_iochibity_IMessage_NOTIFICATION 8L
#ifdef __cplusplus
}
#endif
#endif
