/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_MsgResponseOut */

#ifndef _Included_org_iochibity_MsgResponseOut
#define _Included_org_iochibity_MsgResponseOut
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_MsgResponseOut_INVALID
#define org_iochibity_MsgResponseOut_INVALID 0L
#undef org_iochibity_MsgResponseOut_DISCOVERY
#define org_iochibity_MsgResponseOut_DISCOVERY 1L
#undef org_iochibity_MsgResponseOut_DEVICE
#define org_iochibity_MsgResponseOut_DEVICE 2L
#undef org_iochibity_MsgResponseOut_PLATFORM
#define org_iochibity_MsgResponseOut_PLATFORM 3L
#undef org_iochibity_MsgResponseOut_REPRESENTATION
#define org_iochibity_MsgResponseOut_REPRESENTATION 4L
#undef org_iochibity_MsgResponseOut_SECURITY
#define org_iochibity_MsgResponseOut_SECURITY 5L
#undef org_iochibity_MsgResponseOut_PRESENCE
#define org_iochibity_MsgResponseOut_PRESENCE 6L
#undef org_iochibity_MsgResponseOut_RD
#define org_iochibity_MsgResponseOut_RD 7L
#undef org_iochibity_MsgResponseOut_NOTIFICATION
#define org_iochibity_MsgResponseOut_NOTIFICATION 8L
#ifdef __cplusplus
}
#endif
#endif
