/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Resource_InstanceUuid */

#ifndef _Included_org_iochibity_Resource_InstanceUuid
#define _Included_org_iochibity_Resource_InstanceUuid
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
