/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_CoServiceManager */

#ifndef _Included_org_iochibity_CoServiceManager
#define _Included_org_iochibity_CoServiceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_CoServiceManager
 * Method:    configurePlatformSP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_CoServiceManager_configurePlatformSP
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_iochibity_CoServiceManager
 * Method:    configureDeviceSP
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_CoServiceManager_configureDeviceSP
  (JNIEnv *, jclass, jstring, jobjectArray, jstring, jobjectArray);

/*
 * Class:     org_iochibity_CoServiceManager
 * Method:    registerDefaultCoServiceProvider
 * Signature: (Lorg/iochibity/CoServiceProvider;)Lorg/iochibity/CoServiceProvider;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_CoServiceManager_registerDefaultCoServiceProvider
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_iochibity_CoServiceManager
 * Method:    registerCoServiceProvider
 * Signature: (Lorg/iochibity/CoServiceProvider;)Lorg/iochibity/CoServiceProvider;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_CoServiceManager_registerCoServiceProvider
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_iochibity_CoServiceManager
 * Method:    registeredCoServiceProviders
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_CoServiceManager_registeredCoServiceProviders
  (JNIEnv *, jclass);

/*
 * Class:     org_iochibity_CoServiceManager
 * Method:    getRelatedCoServiceProviders
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_CoServiceManager_getRelatedCoServiceProviders
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
