/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_IServiceProvider */

#ifndef _Included_org_iochibity_IServiceProvider
#define _Included_org_iochibity_IServiceProvider
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
