/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_MsgForServiceProvider */

#ifndef _Included_org_iochibity_MsgForServiceProvider
#define _Included_org_iochibity_MsgForServiceProvider
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_MsgForServiceProvider_INVALID
#define org_iochibity_MsgForServiceProvider_INVALID 0L
#undef org_iochibity_MsgForServiceProvider_DISCOVERY
#define org_iochibity_MsgForServiceProvider_DISCOVERY 1L
#undef org_iochibity_MsgForServiceProvider_DEVICE
#define org_iochibity_MsgForServiceProvider_DEVICE 2L
#undef org_iochibity_MsgForServiceProvider_PLATFORM
#define org_iochibity_MsgForServiceProvider_PLATFORM 3L
#undef org_iochibity_MsgForServiceProvider_REPRESENTATION
#define org_iochibity_MsgForServiceProvider_REPRESENTATION 4L
#undef org_iochibity_MsgForServiceProvider_SECURITY
#define org_iochibity_MsgForServiceProvider_SECURITY 5L
#undef org_iochibity_MsgForServiceProvider_PRESENCE
#define org_iochibity_MsgForServiceProvider_PRESENCE 6L
#undef org_iochibity_MsgForServiceProvider_RD
#define org_iochibity_MsgForServiceProvider_RD 7L
#undef org_iochibity_MsgForServiceProvider_NOTIFICATION
#define org_iochibity_MsgForServiceProvider_NOTIFICATION 8L
/*
 * Class:     org_iochibity_MsgForServiceProvider
 * Method:    getResource
 * Signature: ()Lorg/iochibity/ResourceLocal;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MsgForServiceProvider_getResource
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
