/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_ResourceManager */

#ifndef _Included_org_iochibity_ResourceManager
#define _Included_org_iochibity_ResourceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_ResourceManager
 * Method:    resourceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_ResourceManager_resourceCount
  (JNIEnv *, jclass);

/*
 * Class:     org_iochibity_ResourceManager
 * Method:    registerPlatform
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_ResourceManager_registerPlatform
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_iochibity_ResourceManager
 * Method:    registerDevice
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_ResourceManager_registerDevice
  (JNIEnv *, jclass, jstring, jobjectArray, jstring, jobjectArray);

/*
 * Class:     org_iochibity_ResourceManager
 * Method:    registerDefaultServiceRoutine
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_ResourceManager_registerDefaultServiceRoutine
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_iochibity_ResourceManager
 * Method:    registerResource
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Lorg/iochibity/ResourceServiceProvider;Ljava/lang/Object;B)Lorg/iochibity/ResourceLocal;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ResourceManager_registerResource
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray, jobject, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
