/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Document */

#ifndef _Included_org_iochibity_Document
#define _Included_org_iochibity_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_Document
 * Method:    getPDUPayload
 * Signature: ()Lorg/iochibity/PayloadList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Document_getPDUPayload
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Document
 * Method:    getPayloadType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_Document_getPayloadType
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Document
 * Method:    getOptions
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Document_getOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
