/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_CoServiceProvider */

#ifndef _Included_org_iochibity_CoServiceProvider
#define _Included_org_iochibity_CoServiceProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_CoServiceProvider
 * Method:    exhibitStimulus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iochibity_CoServiceProvider_exhibitStimulus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
