/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_MsgNotificationOut */

#ifndef _Included_org_iochibity_MsgNotificationOut
#define _Included_org_iochibity_MsgNotificationOut
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_MsgNotificationOut_INVALID
#define org_iochibity_MsgNotificationOut_INVALID 0L
#undef org_iochibity_MsgNotificationOut_DISCOVERY
#define org_iochibity_MsgNotificationOut_DISCOVERY 1L
#undef org_iochibity_MsgNotificationOut_DEVICE
#define org_iochibity_MsgNotificationOut_DEVICE 2L
#undef org_iochibity_MsgNotificationOut_PLATFORM
#define org_iochibity_MsgNotificationOut_PLATFORM 3L
#undef org_iochibity_MsgNotificationOut_REPRESENTATION
#define org_iochibity_MsgNotificationOut_REPRESENTATION 4L
#undef org_iochibity_MsgNotificationOut_SECURITY
#define org_iochibity_MsgNotificationOut_SECURITY 5L
#undef org_iochibity_MsgNotificationOut_PRESENCE
#define org_iochibity_MsgNotificationOut_PRESENCE 6L
#undef org_iochibity_MsgNotificationOut_RD
#define org_iochibity_MsgNotificationOut_RD 7L
#undef org_iochibity_MsgNotificationOut_NOTIFICATION
#define org_iochibity_MsgNotificationOut_NOTIFICATION 8L
#ifdef __cplusplus
}
#endif
#endif
