/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Payload */

#ifndef _Included_org_iochibity_Payload
#define _Included_org_iochibity_Payload
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_Payload
 * Method:    setResourceTypes
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_Payload_setResourceTypes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_iochibity_Payload
 * Method:    setInterfaces
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_Payload_setInterfaces
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
