/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_MessageForResource */

#ifndef _Included_org_iochibity_MessageForResource
#define _Included_org_iochibity_MessageForResource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_MessageForResource
 * Method:    getResource
 * Signature: ()Lorg/iochibity/Resource;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageForResource_getResource
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageForResource
 * Method:    getPDUPayload
 * Signature: ()Lorg/iochibity/PayloadList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageForResource_getPDUPayload
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageForResource
 * Method:    getVendorHeaderOptions
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageForResource_getVendorHeaderOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
