/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Observation */

#ifndef _Included_org_iochibity_Observation
#define _Included_org_iochibity_Observation
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_Observation_INVALID
#define org_iochibity_Observation_INVALID 0L
#undef org_iochibity_Observation_DISCOVERY
#define org_iochibity_Observation_DISCOVERY 1L
#undef org_iochibity_Observation_DEVICE
#define org_iochibity_Observation_DEVICE 2L
#undef org_iochibity_Observation_PLATFORM
#define org_iochibity_Observation_PLATFORM 3L
#undef org_iochibity_Observation_REPRESENTATION
#define org_iochibity_Observation_REPRESENTATION 4L
#undef org_iochibity_Observation_SECURITY
#define org_iochibity_Observation_SECURITY 5L
#undef org_iochibity_Observation_PRESENCE
#define org_iochibity_Observation_PRESENCE 6L
#undef org_iochibity_Observation_RD
#define org_iochibity_Observation_RD 7L
#undef org_iochibity_Observation_NOTIFICATION
#define org_iochibity_Observation_NOTIFICATION 8L
/*
 * Class:     org_iochibity_Observation
 * Method:    setResourceTypes
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_Observation_setResourceTypes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_iochibity_Observation
 * Method:    setInterfaces
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_Observation_setInterfaces
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
