/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_MsgRequestOut */

#ifndef _Included_org_iochibity_MsgRequestOut
#define _Included_org_iochibity_MsgRequestOut
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_MsgRequestOut_INVALID
#define org_iochibity_MsgRequestOut_INVALID 0L
#undef org_iochibity_MsgRequestOut_DISCOVERY
#define org_iochibity_MsgRequestOut_DISCOVERY 1L
#undef org_iochibity_MsgRequestOut_DEVICE
#define org_iochibity_MsgRequestOut_DEVICE 2L
#undef org_iochibity_MsgRequestOut_PLATFORM
#define org_iochibity_MsgRequestOut_PLATFORM 3L
#undef org_iochibity_MsgRequestOut_REPRESENTATION
#define org_iochibity_MsgRequestOut_REPRESENTATION 4L
#undef org_iochibity_MsgRequestOut_SECURITY
#define org_iochibity_MsgRequestOut_SECURITY 5L
#undef org_iochibity_MsgRequestOut_PRESENCE
#define org_iochibity_MsgRequestOut_PRESENCE 6L
#undef org_iochibity_MsgRequestOut_RD
#define org_iochibity_MsgRequestOut_RD 7L
#undef org_iochibity_MsgRequestOut_NOTIFICATION
#define org_iochibity_MsgRequestOut_NOTIFICATION 8L
#ifdef __cplusplus
}
#endif
#endif
