/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_ResourceLocal_InstanceString */

#ifndef _Included_org_iochibity_ResourceLocal_InstanceString
#define _Included_org_iochibity_ResourceLocal_InstanceString
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
