/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_exceptions_Util */

#ifndef _Included_org_iochibity_exceptions_Util
#define _Included_org_iochibity_exceptions_Util
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
