/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_ResourceLocal */

#ifndef _Included_org_iochibity_ResourceLocal
#define _Included_org_iochibity_ResourceLocal
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_ResourceLocal_NOMETHOD
#define org_iochibity_ResourceLocal_NOMETHOD 0L
#undef org_iochibity_ResourceLocal_NONE
#define org_iochibity_ResourceLocal_NONE 0L
#undef org_iochibity_ResourceLocal_DISCOVERABLE
#define org_iochibity_ResourceLocal_DISCOVERABLE 1L
#undef org_iochibity_ResourceLocal_OBSERVABLE
#define org_iochibity_ResourceLocal_OBSERVABLE 2L
#undef org_iochibity_ResourceLocal_ACTIVE
#define org_iochibity_ResourceLocal_ACTIVE 4L
#undef org_iochibity_ResourceLocal_SLOW
#define org_iochibity_ResourceLocal_SLOW 8L
#undef org_iochibity_ResourceLocal_SECURE
#define org_iochibity_ResourceLocal_SECURE 16L
#undef org_iochibity_ResourceLocal_EXPLICIT_DISCOVERABLE
#define org_iochibity_ResourceLocal_EXPLICIT_DISCOVERABLE 32L
/*
 * Class:     org_iochibity_ResourceLocal
 * Method:    getTypes
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ResourceLocal_getTypes
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_ResourceLocal
 * Method:    getInterfaces
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ResourceLocal_getInterfaces
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_ResourceLocal
 * Method:    getProperties
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ResourceLocal_getProperties
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_ResourceLocal
 * Method:    getChildren
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ResourceLocal_getChildren
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_ResourceLocal
 * Method:    getServiceProvider
 * Signature: ()Lorg/iochibity/IResourceServiceProvider;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ResourceLocal_getServiceProvider
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_ResourceLocal
 * Method:    getCallbackParam
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ResourceLocal_getCallbackParam
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_ResourceLocal
 * Method:    getActionSet
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ResourceLocal_getActionSet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
