/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_AServiceProvider */

#ifndef _Included_org_iochibity_AServiceProvider
#define _Included_org_iochibity_AServiceProvider
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
