/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_DocForServiceProvider */

#ifndef _Included_org_iochibity_DocForServiceProvider
#define _Included_org_iochibity_DocForServiceProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_DocForServiceProvider
 * Method:    getResource
 * Signature: ()Lorg/iochibity/ResourceLocal;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_DocForServiceProvider_getResource
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_DocForServiceProvider
 * Method:    getPDUPayload
 * Signature: ()Lorg/iochibity/PayloadList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_DocForServiceProvider_getPDUPayload
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_DocForServiceProvider
 * Method:    getVendorHeaderOptions
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_DocForServiceProvider_getVendorHeaderOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
