/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_ServiceProvider */

#ifndef _Included_org_iochibity_ServiceProvider
#define _Included_org_iochibity_ServiceProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_ServiceProvider
 * Method:    react
 * Signature: (Lorg/iochibity/StimulusIn;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_ServiceProvider_react
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_iochibity_ServiceProvider
 * Method:    exhibitBehavior
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iochibity_ServiceProvider_exhibitBehavior
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
