/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_MsgResponseIn */

#ifndef _Included_org_iochibity_MsgResponseIn
#define _Included_org_iochibity_MsgResponseIn
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_MsgResponseIn_INVALID
#define org_iochibity_MsgResponseIn_INVALID 0L
#undef org_iochibity_MsgResponseIn_DISCOVERY
#define org_iochibity_MsgResponseIn_DISCOVERY 1L
#undef org_iochibity_MsgResponseIn_DEVICE
#define org_iochibity_MsgResponseIn_DEVICE 2L
#undef org_iochibity_MsgResponseIn_PLATFORM
#define org_iochibity_MsgResponseIn_PLATFORM 3L
#undef org_iochibity_MsgResponseIn_REPRESENTATION
#define org_iochibity_MsgResponseIn_REPRESENTATION 4L
#undef org_iochibity_MsgResponseIn_SECURITY
#define org_iochibity_MsgResponseIn_SECURITY 5L
#undef org_iochibity_MsgResponseIn_PRESENCE
#define org_iochibity_MsgResponseIn_PRESENCE 6L
#undef org_iochibity_MsgResponseIn_RD
#define org_iochibity_MsgResponseIn_RD 7L
#undef org_iochibity_MsgResponseIn_NOTIFICATION
#define org_iochibity_MsgResponseIn_NOTIFICATION 8L
#ifdef __cplusplus
}
#endif
#endif
