/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_OCF */

#ifndef _Included_org_iochibity_OCF
#define _Included_org_iochibity_OCF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_OCF
 * Method:    Init
 * Signature: (Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_OCF_Init
  (JNIEnv *, jclass, jstring, jint, jint, jstring);

/*
 * Class:     org_iochibity_OCF
 * Method:    OCInit1
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_OCF_OCInit1
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_iochibity_OCF
 * Method:    OCRegisterPersistentStorageHandler
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_OCF_OCRegisterPersistentStorageHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_iochibity_OCF
 * Method:    OCStartMulticastServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iochibity_OCF_OCStartMulticastServer
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_OCF
 * Method:    OCStopMulticastServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iochibity_OCF_OCStopMulticastServer
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_OCF
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iochibity_OCF_run
  (JNIEnv *, jclass);

/*
 * Class:     org_iochibity_OCF
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iochibity_OCF_stop
  (JNIEnv *, jclass);

/*
 * Class:     org_iochibity_OCF
 * Method:    OCCancel
 * Signature: (Ljava/lang/Object;ILjava/lang/Object;B)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_OCF_OCCancel
  (JNIEnv *, jobject, jobject, jint, jobject, jbyte);

/*
 * Class:     org_iochibity_OCF
 * Method:    sendResponse
 * Signature: (Lorg/iochibity/DocResponseOut;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_OCF_sendResponse
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
