/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Message */

#ifndef _Included_org_iochibity_Message
#define _Included_org_iochibity_Message
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_Message
 * Method:    getPayloadList
 * Signature: ()Lorg/iochibity/PayloadList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Message_getPayloadList
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Message
 * Method:    getPayloadType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_Message_getPayloadType
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Message
 * Method:    getOptions
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Message_getOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
