/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Messenger */

#ifndef _Included_org_iochibity_Messenger
#define _Included_org_iochibity_Messenger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_Messenger
 * Method:    sendRequest
 * Signature: (ILorg/iochibity/MsgRequestOut;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_sendRequest__ILorg_iochibity_MsgRequestOut_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_iochibity_Messenger
 * Method:    sendRequest
 * Signature: (ILorg/iochibity/MsgRequestOut;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_sendRequest__ILorg_iochibity_MsgRequestOut_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_iochibity_Messenger
 * Method:    discoverPlatforms
 * Signature: (Lorg/iochibity/MsgRequestOut;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_discoverPlatforms__Lorg_iochibity_MsgRequestOut_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_iochibity_Messenger
 * Method:    discoverPlatforms
 * Signature: (Lorg/iochibity/IResourceServiceRequestor;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_discoverPlatforms__Lorg_iochibity_IResourceServiceRequestor_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_iochibity_Messenger
 * Method:    discoverPlatforms
 * Signature: (Lorg/iochibity/IResourceServiceRequestor;[Lorg/iochibity/DeviceAddress;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_discoverPlatforms__Lorg_iochibity_IResourceServiceRequestor_2_3Lorg_iochibity_DeviceAddress_2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     org_iochibity_Messenger
 * Method:    discoverDevices
 * Signature: (Lorg/iochibity/MsgRequestOut;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_discoverDevices__Lorg_iochibity_MsgRequestOut_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_iochibity_Messenger
 * Method:    discoverDevices
 * Signature: (Lorg/iochibity/IResourceServiceRequestor;[Lorg/iochibity/DeviceAddress;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_discoverDevices__Lorg_iochibity_IResourceServiceRequestor_2_3Lorg_iochibity_DeviceAddress_2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     org_iochibity_Messenger
 * Method:    discoverResources
 * Signature: (Lorg/iochibity/MsgRequestOut;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_discoverResources__Lorg_iochibity_MsgRequestOut_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_iochibity_Messenger
 * Method:    discoverResources
 * Signature: (Lorg/iochibity/IResourceServiceRequestor;[Lorg/iochibity/DeviceAddress;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_iochibity_Messenger_discoverResources__Lorg_iochibity_IResourceServiceRequestor_2_3Lorg_iochibity_DeviceAddress_2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     org_iochibity_Messenger
 * Method:    sendResponse
 * Signature: (Lorg/iochibity/MsgResponseOut;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_Messenger_sendResponse
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_iochibity_Messenger
 * Method:    sendRequest
 * Signature: (Lorg/iochibity/MsgRequestOut;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_Messenger_sendRequest__Lorg_iochibity_MsgRequestOut_2
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
