/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_ServiceManager */

#ifndef _Included_org_iochibity_ServiceManager
#define _Included_org_iochibity_ServiceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_ServiceManager
 * Method:    configurePlatformSP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_ServiceManager_configurePlatformSP
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_iochibity_ServiceManager
 * Method:    configureDeviceSP
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_ServiceManager_configureDeviceSP
  (JNIEnv *, jclass, jstring, jobjectArray, jstring, jobjectArray);

/*
 * Class:     org_iochibity_ServiceManager
 * Method:    registerServiceProvider
 * Signature: (Lorg/iochibity/ServiceProvider;)Lorg/iochibity/ServiceProvider;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ServiceManager_registerServiceProvider
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_iochibity_ServiceManager
 * Method:    registeredServiceProviders
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ServiceManager_registeredServiceProviders
  (JNIEnv *, jclass);

/*
 * Class:     org_iochibity_ServiceManager
 * Method:    getRelatedServiceProviders
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_ServiceManager_getRelatedServiceProviders
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
