= java c++ api


== Design

This API was designed to meet the following goals:

* Wrap the Iotivity C++ API.


== key types and ops

=== OcPlatform

WARNING: This notion of "OcPlatform" seems to have a tenuous
connection with the OIC notion of platform.

Server-side callbacks:

[source,java]
----
    public interface EntityHandler {
        public EntityHandlerResult handleEntity(OcResourceRequest ocResourceRequest);
    }
----

Client-side callbacks:

[source,java]
----
    public interface OnResourceFoundListener {
        public void onResourceFound(OcResource resource);
    }
    public interface OnDeviceFoundListener {
        public void onDeviceFound(OcRepresentation ocRepresentation);
    }
    public interface OnPlatformFoundListener {
        public void onPlatformFound(OcRepresentation ocRepresentation);
    }
    public interface OnPresenceListener {
        public void onPresence(OcPresenceStatus ocPresenceStatus, int nonce, String hostAddress);
    }
----

The conceptual structure here is unclear. "OnPlatformFound" makes
perfect sense, but why is the "EntityHandler" interface embedded in OcPlatform?

Interfaces can be specified anywhere, and need not be nested in
classes; why not declare these in separate namespaces?  It makes sense
to say that a resource must implement an EntityHandler interface, but
not that it must implement a an OcPlatform.EntityHandler interface.


=== OcResource

"Resources" are registered on servers, and proxied on clients.  The
 `OcResource` class is used to proxy resources;
 are used by clients as server resource
 proxies. They do not capture resource state info (no
 "values"). Discovery queries return Resource values; CRUDN operations
 go through Resource objects, and return Representations.

So OCResource is really a kind of meta-representation; it represents
the resource in terms of its meta data (e.g. type) but does not
represent its state. Its main job is to support CRUDN operations
rather than data.

Client-side operation/callback pairs:

[source,java]
----
    public void get( ..., OnGetListener onGetListener, ...) /* overloaded */
    public interface OnGetListener {
        public void onGetCompleted(List<OcHeaderOption> headerOptionList,
                                   OcRepresentation ocRepresentation);
        public void onGetFailed(Throwable ex);
    }
----

[source,java]
----
   /* put is overloaded but always takes an OcRepresentation and a response handler */
    public void put(OcRepresentation representation,
    	   	        OnPutListener onPutListener, ...)
    public interface OnPutListener {
        public void onPutCompleted(List<OcHeaderOption> headerOptionList,
                                   OcRepresentation ocRepresentation);
        public void onPutFailed(Throwable ex);
    }
----

[source,java]
----
   /* put is overloaded but always takes an OcRepresentation and a response handler */
    public void post(OcRepresentation representation,
     	   	         OnPostListener onPostListener, ...)
    public interface OnPostListener {
        public void onPostCompleted(List<OcHeaderOption> headerOptionList,
                                    OcRepresentation ocRepresentation);
        public void onPostFailed(Throwable ex);
    }
----

[source,java]
----
    public native void deleteResource(OnDeleteListener onDeleteListener)
    public interface OnDeleteListener {
        public void onDeleteCompleted(List<OcHeaderOption> headerOptionList);
        public void onDeleteFailed(Throwable ex);
    }
----

[source,java]
----
   /* "observer" means monitor; overloaded */
    public void observe(ObserveType observeType,... OnObserveListener onObserveListener ...)
    public void cancelObserve()
    public interface OnObserveListener {
        public void onObserveCompleted(List<OcHeaderOption> headerOptionList,
                                       OcRepresentation ocRepresentation,
                                       int sequenceNumber);
        public void onObserveFailed(Throwable ex);
    }
----

C++ implementation:

[source,c++]
----
// c++ API OcResource fields:
 private:
     void setHost(const std::string& host);
     std::weak_ptr<IClientWrapper> m_clientWrapper;
     std::string m_uri;
     OCResourceIdentifier m_resourceId;
     OCDevAddr m_devAddr;
     bool m_useHostString;
     bool m_isObservable;
     bool m_isCollection;
     std::vector<std::string> m_resourceTypes;
     std::vector<std::string> m_interfaces;
     std::vector<std::string> m_children;
     OCDoHandle m_observeHandle;
     HeaderOptions m_headerOptions;
----

Notice there are no "values" (i.e. properties) in an OcResource record.


[source,java]
----
// api/OcPlatform.java
    public interface EntityHandler {
        public EntityHandlerResult handleEntity(OcResourceRequest ocResourceRequest);
    }
----


=== OcRepresentation

Java callbacks:  none.

"Representations" communicate resource state from server to
client. Servers will create an OCRepresentation in response to GET
requests, populating its values map with state data. (More likely,
they will maintain such an OCRepresentation to avoid mem allocs)

[source,c++]
----
// c++ API OCRepresentation fields
private:
    std::string m_host;
    std::string m_uri;
    std::vector<OCRepresentation> m_children;
    mutable std::map<std::string, AttributeValue> m_values;
    std::vector<std::string> m_resourceTypes;
    std::vector<std::string> m_interfaces;
    std::vector<std::string> m_dataModelVersions;
    InterfaceType m_interfaceType;
----

NOTE: The Java API as currently implemented does not expose all of
these fields. For example, the C++ API exposes "getDataModelVersion",
but the Java API does not. Ditto for "getChildren", and several other
operations.


Summary: on server, an resource Language Object (e.g. a java class for
LEDs) will contain an OcRepresentation, and implement the
OcPlatform.EntityHandler callback.

=== OcResourceRequest

NOTE: `OcResourceReqest` is received by the server as a parameter to
the `EntityHandler` callback. It corresponds to an `OcResource` object
on the client side.

[source,java]
----
    public RequestType getRequestType()
    public native Map<String, String> getQueryParameters();
    public EnumSet<RequestHandlerFlag> getRequestHandlerFlagSet()
    public native OcRepresentation getResourceRepresentation();
    public native ObservationInfo getObservationInfo();
    public native void setResourceUri(String resourceUri);
    public native String getResourceUri();
    public native List<OcHeaderOption> getHeaderOptions();
    public native OcRequestHandle getRequestHandle();
    public native OcResourceHandle getResourceHandle();

----

=== OcResourceResponse

NOTE: `OcResourceResponse` is created by the server as part of
EntityHandler processing, and sent to the requesting client.  On the
client side, the `OcResourceResponse` is received as parameters to the
client response handling callbacks (the `onXListener` interfaces
above), one `HeaderOptions` andone `OcRepresentation`.

[source,java]
----
    public native String getNewResourceUri();
    public native void setNewResourceUri(String newResourceUri);
    public void setHeaderOptions(List<OcHeaderOption> headerOptionList)
    public native void setRequestHandle(OcRequestHandle ocRequestHandle);
    public native void setResourceHandle(OcResourceHandle ocResourceHandle);
    public void setResponseResult(EntityHandlerResult responseResult)
    public native void setResourceRepresentation(OcRepresentation ocRepresentation,
                                                 String interfaceStr);
    public void setResourceRepresentation(OcRepresentation representation) {

----

NOTE: `EntityHandlerResult` is a result code enum (OK,
RESOURCE_CREATED, etc.), not a result datum.
