/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_constants_OCQualityOfService */

#ifndef _Included_org_iochibity_constants_OCQualityOfService
#define _Included_org_iochibity_constants_OCQualityOfService
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_constants_OCQualityOfService_LOW
#define org_iochibity_constants_OCQualityOfService_LOW 0L
#undef org_iochibity_constants_OCQualityOfService_MEDIUM
#define org_iochibity_constants_OCQualityOfService_MEDIUM 1L
#undef org_iochibity_constants_OCQualityOfService_HIGH
#define org_iochibity_constants_OCQualityOfService_HIGH 2L
#undef org_iochibity_constants_OCQualityOfService_NA
#define org_iochibity_constants_OCQualityOfService_NA 3L
#ifdef __cplusplus
}
#endif
#endif
