/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_exceptions_JNIRuntimeException */

#ifndef _Included_org_iochibity_exceptions_JNIRuntimeException
#define _Included_org_iochibity_exceptions_JNIRuntimeException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_exceptions_JNIRuntimeException_serialVersionUID
#define org_iochibity_exceptions_JNIRuntimeException_serialVersionUID -3042686055658047285LL
#undef org_iochibity_exceptions_JNIRuntimeException_serialVersionUID
#define org_iochibity_exceptions_JNIRuntimeException_serialVersionUID -3387516993124229948LL
#undef org_iochibity_exceptions_JNIRuntimeException_serialVersionUID
#define org_iochibity_exceptions_JNIRuntimeException_serialVersionUID -7034897190745766939LL
#ifdef __cplusplus
}
#endif
#endif
