/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_PayloadForResourceState */

#ifndef _Included_org_iochibity_PayloadForResourceState
#define _Included_org_iochibity_PayloadForResourceState
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_PayloadForResourceState_INVALID
#define org_iochibity_PayloadForResourceState_INVALID 0L
#undef org_iochibity_PayloadForResourceState_DISCOVERY
#define org_iochibity_PayloadForResourceState_DISCOVERY 1L
#undef org_iochibity_PayloadForResourceState_DEVICE
#define org_iochibity_PayloadForResourceState_DEVICE 2L
#undef org_iochibity_PayloadForResourceState_PLATFORM
#define org_iochibity_PayloadForResourceState_PLATFORM 3L
#undef org_iochibity_PayloadForResourceState_REPRESENTATION
#define org_iochibity_PayloadForResourceState_REPRESENTATION 4L
#undef org_iochibity_PayloadForResourceState_SECURITY
#define org_iochibity_PayloadForResourceState_SECURITY 5L
#undef org_iochibity_PayloadForResourceState_PRESENCE
#define org_iochibity_PayloadForResourceState_PRESENCE 6L
#undef org_iochibity_PayloadForResourceState_RD
#define org_iochibity_PayloadForResourceState_RD 7L
/*
 * Class:     org_iochibity_PayloadForResourceState
 * Method:    createPayload
 * Signature: (Lorg/iochibity/Resource;)Lorg/iochibity/PayloadForResourceState;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_PayloadForResourceState_createPayload
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_iochibity_PayloadForResourceState
 * Method:    setResourceTypes
 * Signature: (Ljava/util/LinkedList;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_PayloadForResourceState_setResourceTypes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_iochibity_PayloadForResourceState
 * Method:    setInterfaces
 * Signature: (Ljava/util/LinkedList;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_PayloadForResourceState_setInterfaces
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_iochibity_PayloadForResourceState
 * Method:    setProperties
 * Signature: (Lorg/iochibity/PropertyForResource;)V
 */
JNIEXPORT void JNICALL Java_org_iochibity_PayloadForResourceState_setProperties
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
