/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Response */

#ifndef _Included_org_iochibity_Response
#define _Included_org_iochibity_Response
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_Response
 * Method:    getResource
 * Signature: ()Lorg/iochibity/Resource;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Response_getResource
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Response
 * Method:    getPayload
 * Signature: ()Lorg/iochibity/Payload;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Response_getPayload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
