/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_MessageService */

#ifndef _Included_org_iochibity_MessageService
#define _Included_org_iochibity_MessageService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_MessageService
 * Method:    getResource
 * Signature: ()Lorg/iochibity/Resource;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getResource
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getPayload
 * Signature: ()Lorg/iochibity/Payload;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getPayload
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getTypes
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getTypes
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getInterfaces
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getInterfaces
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getProperties
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getProperties
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getChildren
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getChildren
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getServiceProvider
 * Signature: ()Lorg/iochibity/ResourceServiceProvider;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getServiceProvider
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getCallbackParam
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getCallbackParam
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getPolicies
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_MessageService_getPolicies
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_MessageService
 * Method:    getVendorHeaderOptions
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_MessageService_getVendorHeaderOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
