/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_ResourceManager */

#ifndef _Included_org_iochibity_ResourceManager
#define _Included_org_iochibity_ResourceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_ResourceManager
 * Method:    resourceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_ResourceManager_resourceCount
  (JNIEnv *, jclass);

/*
 * Class:     org_iochibity_ResourceManager
 * Method:    registerDefaultServiceRoutine
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_ResourceManager_registerDefaultServiceRoutine
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_iochibity_ResourceManager
 * Method:    registerResource
 * Signature: (Lorg/iochibity/Resource;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/iochibity/ResourceServiceProvider;Ljava/lang/Object;B)I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_ResourceManager_registerResource
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jobject, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
