/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_RequestIn */

#ifndef _Included_org_iochibity_RequestIn
#define _Included_org_iochibity_RequestIn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_RequestIn
 * Method:    getResource
 * Signature: ()Lorg/iochibity/Resource;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_RequestIn_getResource
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_RequestIn
 * Method:    getDeviceAddress
 * Signature: ()Lorg/iochibity/DeviceAddress;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_RequestIn_getDeviceAddress
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_RequestIn
 * Method:    getPayload
 * Signature: ()Lorg/iochibity/Payload;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_RequestIn_getPayload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
