/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_constants_OCMode */

#ifndef _Included_org_iochibity_constants_OCMode
#define _Included_org_iochibity_constants_OCMode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_constants_OCMode_CLIENT
#define org_iochibity_constants_OCMode_CLIENT 0L
#undef org_iochibity_constants_OCMode_SERVER
#define org_iochibity_constants_OCMode_SERVER 1L
#undef org_iochibity_constants_OCMode_CLIENT_SERVER
#define org_iochibity_constants_OCMode_CLIENT_SERVER 2L
#undef org_iochibity_constants_OCMode_GATEWAY
#define org_iochibity_constants_OCMode_GATEWAY 3L
#ifdef __cplusplus
}
#endif
#endif
