/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Resource_InstanceId */

#ifndef _Included_org_iochibity_Resource_InstanceId
#define _Included_org_iochibity_Resource_InstanceId
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
