/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_TypeList */

#ifndef _Included_org_iochibity_TypeList
#define _Included_org_iochibity_TypeList
#ifdef __cplusplus
extern "C" {
#endif
#undef org_iochibity_TypeList_MAX_ARRAY_SIZE
#define org_iochibity_TypeList_MAX_ARRAY_SIZE 2147483639L
#undef org_iochibity_TypeList_serialVersionUID
#define org_iochibity_TypeList_serialVersionUID 876323262645176354LL
#ifdef __cplusplus
}
#endif
#endif
