/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_PayloadForLinks */

#ifndef _Included_org_iochibity_PayloadForLinks
#define _Included_org_iochibity_PayloadForLinks
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
