/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_OCF_ResourceServiceProvider */

#ifndef _Included_org_iochibity_OCF_ResourceServiceProvider
#define _Included_org_iochibity_OCF_ResourceServiceProvider
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
