/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_Resource */

#ifndef _Included_org_iochibity_Resource
#define _Included_org_iochibity_Resource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_Resource
 * Method:    getTypes
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Resource_getTypes
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Resource
 * Method:    getInterfaces
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Resource_getInterfaces
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Resource
 * Method:    getProperties
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Resource_getProperties
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Resource
 * Method:    getChildren
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Resource_getChildren
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Resource
 * Method:    getServiceProvider
 * Signature: ()Lorg/iochibity/ResourceServiceProvider;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Resource_getServiceProvider
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Resource
 * Method:    getCallbackParam
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_Resource_getCallbackParam
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_Resource
 * Method:    getPolicies
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_Resource_getPolicies
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
