/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iochibity_PayloadResource */

#ifndef _Included_org_iochibity_PayloadResource
#define _Included_org_iochibity_PayloadResource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iochibity_PayloadResource
 * Method:    getTypes
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_PayloadResource_getTypes
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_PayloadResource
 * Method:    getInterfaces
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_PayloadResource_getInterfaces
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_PayloadResource
 * Method:    getProperties
 * Signature: ()Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_org_iochibity_PayloadResource_getProperties
  (JNIEnv *, jobject);

/*
 * Class:     org_iochibity_PayloadResource
 * Method:    setUri
 * Signature: (Lorg/iochibity/PayloadResource;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_iochibity_PayloadResource_setUri
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_iochibity_PayloadResource
 * Method:    putInt
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_iochibity_PayloadResource_putInt
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     org_iochibity_PayloadResource
 * Method:    getInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_iochibity_PayloadResource_getInt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_iochibity_PayloadResource
 * Method:    setPropDouble
 * Signature: (Ljava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_iochibity_PayloadResource_setPropDouble
  (JNIEnv *, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
