= java wrapper on c api

== build

First source devhost and targethost files, e.g.

```
source ~/xc/source.me/darwin.devhost
source ~/xc/source.me/darwin.targethost
```

$ scons jni-c
options:  VERBOSE=0 | 1, LOGGING= 0 | 1

$ cd jni-c
$ mvn install

== examples

The run the example:

$ cd examples
$ export MAVEN_OPTS="-Djava.library.path=${INSTALL_SYSROOT}/lib"
$ mvn exec:java -Dexec.mainClass="org.iochibity.test.OCFTestClient"
or
$ mvn exec:java -Dexec.mainClass="org.iochibity.test.OCFTestServer"

== naming conventions


JNI:

* 'klass' is reserved for the jclass arg (Class object) of static methods
* 'this' is reserved for the (this) jobject arg of object methods
* k_  is the prefix used for klasses other than the klass object
* fid_ is the prefix for field ids from GetFieldId, e.g. fid_class_method
* mid_ is the prefix for method ids from GetMethodId, e.g. mid_class_method
* mids_ is for static methods
* j_ - prefix for java objects
* c_ - prefix for native c data

UPPER_CASE prefixes: file scope, for caching; e.g. K_PAYLOAD.


Java:

* _ - underscore prefix marks a field as both private and
  corresponding to an underlying var, ptr, struct, e.g. _handle


== exceptions

Instead of returning an OCStackResult code we return void and throw
Java exceptions as needed.


== mapping to iotivity c api

Metaphor: bureaucracy.  Documents contain (inscribed) messages.
ServiceProviders (respondants) receive (from ServiceRequestors)
incoming request documents (DocRequestIn), which refer to Resources
(ResourceLocal).  They create an outgoing document (DocResponseOut)
and send it to the ServiceRequestor.

Resources:
ServiceRequestors create outgoing request documents (DocRequestOut)
and send them to a ServiceProvider.  receive (from ServiceProviders)
incoming response documents (DocResponseIn)



setPlatformInfo  => ResourceManager.registerPlatform
setDeviceInfo    => ResourceManager.registerDevice
OCCreateResource => ResourceManager.registerResource
OCDoResource     => ResourceManager.sendRequest

OCResource       => Resource
			        ResourceLocal  (new; resource on server)
			        ResourceRemote (new; resource on client, rec'd from server)

new: Document
new: DocForServiceProvider extends Document
OCEntityHandlerRequest   => DocRequestIn   extends DocForServiceProvider
OCEntityHandlerResponse  => DocResponseOut extends DocForServiceProvider

new: DocForServiceRequestor extends Document
OCClientResponse         => DocResponseIn  extends DocForServiceRequestor
new:                        DocReQuestOut  extends DocForServiceRequestor
