local_repository(
	name = "openocf",
	path = "/Users/gar/openocf",
)

new_local_repository(
  name = "toolchain_ndk",
  path = "/Users/gar/android/android-ndk-r14b",
  build_file = 'platforms/ndk/toolchain.BUILD',
)

# new_local_repository(
#   name = "cosysroot_ndk",
#   path = "/Users/gar/cosysroots/ndk",
#   build_file = "platforms/ndk/cosysroot.BUILD"
# )

android_sdk_repository(
    name="androidsdk",
    path="/Users/gar/android/sdk",
    api_level=22,
    # build_tools_version="27.0.0"
)

android_ndk_repository(
    name="androidndk",
    path="/Users/gar/android/android-ndk-r14b",
    api_level=23,
)

