/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_signals_IBehavior */

#ifndef _Included_openocf_signals_IBehavior
#define _Included_openocf_signals_IBehavior
#ifdef __cplusplus
extern "C" {
#endif
#undef openocf_signals_IBehavior_INVALID
#define openocf_signals_IBehavior_INVALID 0L
#undef openocf_signals_IBehavior_DISCOVERY
#define openocf_signals_IBehavior_DISCOVERY 1L
#undef openocf_signals_IBehavior_DEVICE
#define openocf_signals_IBehavior_DEVICE 2L
#undef openocf_signals_IBehavior_PLATFORM
#define openocf_signals_IBehavior_PLATFORM 3L
#undef openocf_signals_IBehavior_REPRESENTATION
#define openocf_signals_IBehavior_REPRESENTATION 4L
#undef openocf_signals_IBehavior_SECURITY
#define openocf_signals_IBehavior_SECURITY 5L
#undef openocf_signals_IBehavior_PRESENCE
#define openocf_signals_IBehavior_PRESENCE 6L
#undef openocf_signals_IBehavior_RD
#define openocf_signals_IBehavior_RD 7L
#undef openocf_signals_IBehavior_NOTIFICATION
#define openocf_signals_IBehavior_NOTIFICATION 8L
#ifdef __cplusplus
}
#endif
#endif
