/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_app_IResourceSP */

#ifndef _Included_openocf_app_IResourceSP
#define _Included_openocf_app_IResourceSP
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
