/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_signals_Behavior */

#ifndef _Included_openocf_signals_Behavior
#define _Included_openocf_signals_Behavior
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openocf_signals_Behavior
 * Method:    getObservationRecords
 * Signature: ()Lopenocf/signals/ObservationList;
 */
JNIEXPORT jobject JNICALL Java_openocf_signals_Behavior_getObservationRecords
  (JNIEnv *, jobject);

/*
 * Class:     openocf_signals_Behavior
 * Method:    getOptions
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_openocf_signals_Behavior_getOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
