/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_app_DefaultCoRSP */

#ifndef _Included_openocf_app_DefaultCoRSP
#define _Included_openocf_app_DefaultCoRSP
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
