/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_app_CoResourceSP */

#ifndef _Included_openocf_app_CoResourceSP
#define _Included_openocf_app_CoResourceSP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openocf_app_CoResourceSP
 * Method:    ctorCoSP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openocf_app_CoResourceSP_ctorCoSP
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    getMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_app_CoResourceSP_getMethod
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    setMethod
 * Signature: (I)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_setMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    getUri
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openocf_app_CoResourceSP_getUri
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    setUri
 * Signature: (Ljava/lang/String;)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_setUri
  (JNIEnv *, jobject, jstring);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    getIPAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openocf_app_CoResourceSP_getIPAddress
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    getBLEAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openocf_app_CoResourceSP_getBLEAddress
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    getPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_app_CoResourceSP_getPort
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    getNetworkAdapter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_app_CoResourceSP_getNetworkAdapter
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    getNetworkFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_app_CoResourceSP_getNetworkFlags
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    isTransportSecure
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_isTransportSecure
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    setTransportSecure
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_setTransportSecure
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    isTransportUDP
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_isTransportUDP
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    setTransportUDP
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_setTransportUDP
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    isTransportTCP
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_isTransportTCP
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    setTransportTCP
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_setTransportTCP
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    isTransportGATT
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_isTransportGATT
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    setTransportGATT
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_setTransportGATT
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    isTransportRFCOMM
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_isTransportRFCOMM
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    setTransportRFCOMM
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_setTransportRFCOMM
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    isTransportNFC
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_isTransportNFC
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    setTransportNFC
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_setTransportNFC
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    networkIsIP
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_networkIsIP__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    networkIsIP
 * Signature: (Z)Lopenocf/app/ICoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_networkIsIP__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    networkIsIPv4
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_networkIsIPv4__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    networkIsIPv4
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_networkIsIPv4__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    networkIsIPv6
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_networkIsIPv6__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    networkIsIPv6
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_networkIsIPv6__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsInterface
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_scopeIsInterface__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsInterface
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_scopeIsInterface__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsLink
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_scopeIsLink__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsLink
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_scopeIsLink__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsRealm
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_scopeIsRealm__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsRealm
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_scopeIsRealm__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsAdmin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_scopeIsAdmin__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsAdmin
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_scopeIsAdmin__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsSite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_scopeIsSite__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsSite
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_scopeIsSite__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsOrg
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_scopeIsOrg__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsOrg
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_scopeIsOrg__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsGlobal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_scopeIsGlobal__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    scopeIsGlobal
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_scopeIsGlobal__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    routingIsMulticast
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_app_CoResourceSP_routingIsMulticast__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    routingIsMulticast
 * Signature: (Z)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_routingIsMulticast__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    qualityOfService
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_app_CoResourceSP_qualityOfService__
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    qualityOfService
 * Signature: (I)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_qualityOfService__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    coAddress
 * Signature: ()Lopenocf/utils/EndPoint;
 */
JNIEXPORT jobject JNICALL Java_openocf_app_CoResourceSP_coAddress
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_CoResourceSP
 * Method:    deactivate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openocf_app_CoResourceSP_deactivate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
