/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_engine_OCFServerSP */

#ifndef _Included_openocf_engine_OCFServerSP
#define _Included_openocf_engine_OCFServerSP
#ifdef __cplusplus
extern "C" {
#endif
#undef openocf_engine_OCFServerSP_CLIENT
#define openocf_engine_OCFServerSP_CLIENT 0L
#undef openocf_engine_OCFServerSP_SERVER
#define openocf_engine_OCFServerSP_SERVER 1L
#undef openocf_engine_OCFServerSP_CLIENT_SERVER
#define openocf_engine_OCFServerSP_CLIENT_SERVER 2L
#undef openocf_engine_OCFServerSP_GATEWAY
#define openocf_engine_OCFServerSP_GATEWAY 3L
#undef openocf_engine_OCFServerSP_QOS_LOW
#define openocf_engine_OCFServerSP_QOS_LOW 0L
#undef openocf_engine_OCFServerSP_QOS_MEDIUM
#define openocf_engine_OCFServerSP_QOS_MEDIUM 1L
#undef openocf_engine_OCFServerSP_QOS_HIGH
#define openocf_engine_OCFServerSP_QOS_HIGH 2L
#undef openocf_engine_OCFServerSP_QOS_NA
#define openocf_engine_OCFServerSP_QOS_NA 3L
/*
 * Class:     openocf_engine_OCFServerSP
 * Method:    exhibit
 * Signature: (Lopenocf/app/ResourceSP;)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFServerSP_exhibit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openocf_engine_OCFServerSP
 * Method:    configurePlatformSP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFServerSP_configurePlatformSP
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     openocf_engine_OCFServerSP
 * Method:    configureDeviceSP
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFServerSP_configureDeviceSP
  (JNIEnv *, jclass, jstring, jobjectArray, jstring, jobjectArray);

/*
 * Class:     openocf_engine_OCFServerSP
 * Method:    registerResourceSP
 * Signature: (Lopenocf/app/ResourceSP;)Lopenocf/app/ResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_engine_OCFServerSP_registerResourceSP
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openocf_engine_OCFServerSP
 * Method:    registeredResourceSPs
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_openocf_engine_OCFServerSP_registeredResourceSPs
  (JNIEnv *, jclass);

/*
 * Class:     openocf_engine_OCFServerSP
 * Method:    getRelatedResourceSPs
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_openocf_engine_OCFServerSP_getRelatedResourceSPs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
