/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_utils_EndPoint */

#ifndef _Included_openocf_utils_EndPoint
#define _Included_openocf_utils_EndPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openocf_utils_EndPoint
 * Method:    networkProtocol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_utils_EndPoint_networkProtocol
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    networkFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_utils_EndPoint_networkFlags
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    transportIsSecure
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_utils_EndPoint_transportIsSecure
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    isIPv4
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_utils_EndPoint_isIPv4
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    isIPv6
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_utils_EndPoint_isIPv6
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    isMulticast
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_openocf_utils_EndPoint_isMulticast
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    networkScope
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_openocf_utils_EndPoint_networkScope
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_utils_EndPoint_port
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    ipAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openocf_utils_EndPoint_ipAddress
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    ifindex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_utils_EndPoint_ifindex
  (JNIEnv *, jobject);

/*
 * Class:     openocf_utils_EndPoint
 * Method:    routeData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openocf_utils_EndPoint_routeData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
