/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_signals_Observable */

#ifndef _Included_openocf_signals_Observable
#define _Included_openocf_signals_Observable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
