/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_standard_OCFServices */

#ifndef _Included_openocf_standard_OCFServices
#define _Included_openocf_standard_OCFServices
#ifdef __cplusplus
extern "C" {
#endif
#undef openocf_standard_OCFServices_CLIENT
#define openocf_standard_OCFServices_CLIENT 0L
#undef openocf_standard_OCFServices_SERVER
#define openocf_standard_OCFServices_SERVER 1L
#undef openocf_standard_OCFServices_CLIENT_SERVER
#define openocf_standard_OCFServices_CLIENT_SERVER 2L
#undef openocf_standard_OCFServices_GATEWAY
#define openocf_standard_OCFServices_GATEWAY 3L
#undef openocf_standard_OCFServices_QOS_LOW
#define openocf_standard_OCFServices_QOS_LOW 0L
#undef openocf_standard_OCFServices_QOS_MEDIUM
#define openocf_standard_OCFServices_QOS_MEDIUM 1L
#undef openocf_standard_OCFServices_QOS_HIGH
#define openocf_standard_OCFServices_QOS_HIGH 2L
#undef openocf_standard_OCFServices_QOS_NA
#define openocf_standard_OCFServices_QOS_NA 3L
/*
 * Class:     openocf_standard_OCFServices
 * Method:    config_logging
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_openocf_standard_OCFServices_config_1logging
  (JNIEnv *, jclass, jstring);

/*
 * Class:     openocf_standard_OCFServices
 * Method:    config_svrs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_openocf_standard_OCFServices_config_1svrs
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
