/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_signals_IMessage */

#ifndef _Included_openocf_signals_IMessage
#define _Included_openocf_signals_IMessage
#ifdef __cplusplus
extern "C" {
#endif
#undef openocf_signals_IMessage_INVALID
#define openocf_signals_IMessage_INVALID 0L
#undef openocf_signals_IMessage_DISCOVERY
#define openocf_signals_IMessage_DISCOVERY 1L
#undef openocf_signals_IMessage_DEVICE
#define openocf_signals_IMessage_DEVICE 2L
#undef openocf_signals_IMessage_PLATFORM
#define openocf_signals_IMessage_PLATFORM 3L
#undef openocf_signals_IMessage_REPRESENTATION
#define openocf_signals_IMessage_REPRESENTATION 4L
#undef openocf_signals_IMessage_SECURITY
#define openocf_signals_IMessage_SECURITY 5L
#undef openocf_signals_IMessage_PRESENCE
#define openocf_signals_IMessage_PRESENCE 6L
#undef openocf_signals_IMessage_RD
#define openocf_signals_IMessage_RD 7L
#undef openocf_signals_IMessage_NOTIFICATION
#define openocf_signals_IMessage_NOTIFICATION 8L
#ifdef __cplusplus
}
#endif
#endif
