/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_signals_InboundStimulus */

#ifndef _Included_openocf_signals_InboundStimulus
#define _Included_openocf_signals_InboundStimulus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
