/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_signals_Message */

#ifndef _Included_openocf_signals_Message
#define _Included_openocf_signals_Message
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openocf_signals_Message
 * Method:    getObservationRecords
 * Signature: ()Lopenocf/signals/ObservationList;
 */
JNIEXPORT jobject JNICALL Java_openocf_signals_Message_getObservationRecords
  (JNIEnv *, jobject);

/*
 * Class:     openocf_signals_Message
 * Method:    getOptions
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_openocf_signals_Message_getOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
