/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_app_ResourceSP */

#ifndef _Included_openocf_app_ResourceSP
#define _Included_openocf_app_ResourceSP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openocf_app_ResourceSP
 * Method:    exhibit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openocf_app_ResourceSP_exhibit
  (JNIEnv *, jobject);

/*
 * Class:     openocf_app_ResourceSP
 * Method:    method
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openocf_app_ResourceSP_method
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
