/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_signals_ObservationList */

#ifndef _Included_openocf_signals_ObservationList
#define _Included_openocf_signals_ObservationList
#ifdef __cplusplus
extern "C" {
#endif
#undef openocf_signals_ObservationList_MAX_ARRAY_SIZE
#define openocf_signals_ObservationList_MAX_ARRAY_SIZE 2147483639L
#undef openocf_signals_ObservationList_serialVersionUID
#define openocf_signals_ObservationList_serialVersionUID 876323262645176354LL
#ifdef __cplusplus
}
#endif
#endif
