= jni-c design considerations

* <<goals,goals>>
* <<nongoals,non-goals>>
* <<conceptoverview,C API: conceptual overview>>
** <<serverside,server side>>
** <<clientside,client side>>
* <<rethink,rethink>>

== [[goals]]goals

* Minimalism.  This is a 100% C, direct-to-c-api implementation.  It's
  a wrapper around the Iotivity C API; the C++ API is not used.
* Alignment with the OCF (OIC) protocol specification.  The Iotivity C
  API terminology (var and function names) deviates from the language
  of the protocol specification.
* Conceptual clarity. The Iotivity C API uses some rather opaque
  names, like "OCDoResource", which really should be something like
  "sendRequest".
* Simplicity.  The C API exposes a lot of detail that application
  programmers should not have to worry about.  The jni-c API tries to
  minimize this.
* Consistency.  The C API has consistency problems; the same thing is
  referred to by different names alarmingly often.  For example, the
  list of interfaces associated with a resource is sometimes
  "interfaces", sometimes "ifaces" and sometimes "ifs".  Resource
  properties are called "properties" in some places, and "attributes"
  in others.  Etc.
* Symmetry.  The C API obscures the many symmetries involved in the
  Client-Server model; for example, it calls the incoming message
  handled by servers "OCEntityHandlerRequest", and the incoming
  message handled by clients "OCClientResponse", which I find just
  confusing.  The jni-c API uses "MsgRequestIn" and "MsgResponseIn",
  respectively.  See the link:jni-c/README.adoc[jni-c README] for more details.
* Implementation independence. Works with both
  https://www.iotivity.org/[Iotivity] (version 1.2.1) and
  https://github.com/iotk/iochibity[Iochibity].


== [[nongoals]]non-goals

* One-to-one mirroring of the C API
* Performance.  We will optimize later; for now, the goals of
  simplicity, conceptual clarity, etc. take priority.

== [[conceptoverview]]C API: conceptual overview


Here is a rough overview of how the Iotivity C API works:

=== [[serverside]]server side

The first step (aside from initializing the "stack"), is to create a
"Resource" using `OCCreateResource`.  The service routine responsible
for handling incoming requests on the resource is passed as a
parameter of type `OCEntityHandler` (a function pointer).

Creating a resource has the side-effect of inserting the created
resource into the global list of resources maintained by the stack;
this effectively registers the resource and its service routine with
an implicit "ServiceManager".

A second, implicit, side-effect of creating (registering) a resource
is that the resource effectively begins "listening" for incoming
requests.  This is implicit, because the actual mechanism is rather
complicated.  Resources do not actually do any active listening; that
happens way down in the communications layers of the stack.  In fact,
the listening mechanism is set up by the `Init1` routine, which, among
other tasks, starts the thread that will actually listen for incoming
messages by calling `CAInitialize`, as well as initializing the
stack's message dispatching mechanism.  Registering a resource
effectively makes it available for dispatch, so in a sense this can be
thought of as enabling the resource as a listener.  Dispatch of actual
messages is the responsiblity of `OCProcess`; calling that routine in
a loop is the last step in enabling resources as message handlers.

The stack will then dispatch incoming messages to the resource's
service routine.  That routine is responsible for creating a response
(`OCEntityHandlerResponse`) and sending it to the client (`OCDoResponse`).

=== [[clientside]]client side

The client, after initializing the stack (`Init` or `Init1`), sends a
request to the server by calling `OCDoResource`.  The service routine
responsible for handling response messages is passed as a parameter in
the form of a function pointer of type `OCClientResponseHandler`.

Like `OCCreateResource` on the server side, `OCDoResource` on the
client side several key side-effects.  First of all, it creates a
request message (`CARequestInfo_t`); this data structure will be sent
to the server, where it will be reconstructed as a
`OCEntityHandlerRequest` structure and passed to the resource's
service routine (`OCEntityHandler`).

The second side-effect of `OCDoResource`, parallel to registration of
a resource on the server side, is insertion of the client's service
routine (`OCClientResponseHandler`) in the global list of client
callbacks maintained by the stack.  This list will be used by the
client-side listening mechanism to enable dispatch of incoming
responses to the correct service routine.  As in the case of resource
registration on the server side, this has the implicit side-effect of
enabling the client "resource" as a listener.

For obvious reasons, the actual sending of the outgoing request
message by `OCDoResource` happens _after_ the `CARequestInfo_t`
message is created and client's service routine is registered.

As in the case on the server side, the message listening mechanism is
set up by the `Init1` routine, and calling `OCDoResource` makes the
client service routine available for dispatch.  Dispatch of incoming
messages is again the job of `OCProcess`, which is called as the last
step in starting up a client.

== [[rethink]]rethink

The structure of the C API works, but it tends to obscure the deep
symmetries involved in the client-server model.  With a little
conceptual tinkering and some judicious terminology, we can bring
those symmetries to the surface, and thus simplfy and clarify the
programming model.

Dualism.  At risk of sounding pedantic, it's useful to think in terms
of _thing_ and _co-thing_.  (The idea comes from category theory.)

=== Message and CoMessage

Considered in isolation, a message is a message is a message.  But in
a client-server world, messages always come in pairs:
request-response, request-notification.  Message and CoMessage.

In Iochibity jni-c, we use the following terms:

* Message (base class)
* MsgRequestOut       (sent by client; abstracts over implicit CARequestInfo_t)
* MsgRequestIn        (received by server; abstracts over OCEntityHandlerRequest)
* MsgResponseOut      (sent by server; abstracts over OCEntityHandlerResponse)
* MsgResponseIn       (received by client; abstracts over OCClientResponse)
* MsgNotificationOut  (sent by server)
* MsgNotificationIn   (received by client)


=== Service and CoService

Servers _service_ (i.e. handle) incoming request messages; clients
_co-service_ incoming response co-messages.

The difference is that the service routine on a server is normally
responsible for creating a response message and sending it to the
client.  Client co-service routines normally do not themselves respond
to incoming response co-messages.

Iochibity jni-c terminology:

* serviceMsgRequestIn      (server-side, abstracts over OCEntityHandler)
* serviceMsgResponseIn     (client-side, abstracts over OCClientResponseHandler)
* serviceMsgNotificationIn (client-side)

=== ServiceProvider and CoServiceProvider

What Iotivity calls a "Resource" on the server-side is better thought
of as a _ServiceProvider_.  A ServiceProvider, like an `OCResource`,
comprises a collection of (state) data and meta-data, plus a service
routine.  The motivation for the terminology is simple: "Resource"
purports to say what a thing is, but it is so abstract and vague as to
be effectively information-free.  "ServiceProvider", by contrast,
accurately describes what the thing _does_, which is what is really
important.

The client-side dual of a ServiceProvider is a CoServiceProvider, or
more informally, a ServiceRequestor or ServiceConsumer.  The
motivation for the terminology is conceptual; clients (co-)service
(i.e. handle) incoming response (co-)messages, just as
ServiceProviders service incoming request messages.

In Iotivity terms, a CoServiceProvider is the client-side "entity"
that sends requests to servers and handles their responses.  However,
Iotivity does not explicity support this abstraction; there is no
`OCClientResource` or similar corresponding to `OCResource` on the
server-side.  But it is clearly implicit in client operations.

The concepts of ServiceProvider and CoServiceProvider bring out the
duality of client and server operations.  In both cases, we have
service routines responsible handle incoming messages, and in both
cases we send outgoing messages.  The contrast is that
ServiceProviders send responses after receiving requests, whereas
CoServiceProviders send requests before receiving responses.

Iochibity jni-c terminology:

* ServiceProvider
* CoServiceProvider    (aka ServiceRequestor)


=== against "representation"

Iotivity uses the notion of "representation" to describe responses to
requests on resources.  The "payload" of such a response is encoded as
`OCRepPayload` structure.

Iochibity jni-c eschews talk of "representation" for the same reason
it eschews talk of "resource": the concept is too abstract and vague
to be useful.  In software, everything can be thought of as a
representation of something, one way or another.

The notion is also, arguably, just wrong.  Its common use in the Web
world reflects a deep semoitic confusion.  The resource/representation
mythology would have it that the payload in a response represents the
resource; but that is a fundamentally misguided idea.  It conflates
the white-box model associated with Turing computation and the
black-box model that is central to interactionist models of
computation.

_There is no principled justfication for the claim that such payloads
represent the state of a resource!_ Compare smoke and fire; smoke is a
_signal_ of fire, but it would be a fundamental error to say that
smoke _represents_ fire.  But the response of a server is better
thought of the smoke that "signals" the resource.

_The observable properties and behaviors of a black box have no
intrinsic representational relation to the internal state and
processes of the box!_ To see this just imagine observing a black box
whose behavior is random.  Every time you "read" the box you get a
different and unpredictable value, on that has no deterministic
relation to the internals of the box (which could be entirely
deterministic.)

Aside from vagueness, a problem with talk of resources and
representations is that it obscures the underlying computational
model, which is an interactionist rather than a Turing Machine model.



NOTE: TODO: clarify the black-box model, state machines and
observation, interactional computation model, etc.


=== Observation and CoObservation

WARNING: Iochibity jni-c does _not_ use "observe" and cognate terms in
the way Iotivity uses them.

The response message created by a ServiceProvider in response to a
request contains, not a representation, but an _observation_.

== interaction: black boxes, reactive systems

An _interaction_ is comprised of the following operations:

* The client _exhibits a stimulus_ (e.g. GET /a/temperature)
* The server _observes the stimulus_
* The server _exhibits a behavior_
* The client _observes the behavior_

Exhibitions are _actions_; observations are _co-actions_.

In response to an observed stimulus, the server may optionally modify
its internal state, but that is irrelevant to the interactionist
model, since it is hidden.  Only what is externally observable
(stimulii, behaviors) is relevant.

Note that exhibition of behavior, like modification of state, is
optional for the server.  For example, if you send a command to
configure a server (e.g. tell a temperature sensor to take a sample
every n minutes), you may receive a response indicating that the
command was successfully processed - the internal state of the server
changed - but the response will probably not exhibit the behavior of
the instrument (it won't contain an observation of the temperature).

The mechanism that supports interactions is a hidden implementation
detail.  In the case of Iotivity, it involves the exchange of request
and response messages over a network transport, but this is optional -
an implementation could also use Unix sockets or some other
inter-process communication mechanism.  It need not even involve
messages as first-class entities.  Even where messages over network
transports are used, the nature of the messages and transport protocol
is unimportant, and normally hidden from the user.

The theoretical fiction is that all four operations involved in an
interaction occur simultaneously and instantaneously.  Think "quantum
entanglement".

In Iochcibity jni-c API, currently, some of the implementation details
are exposed.  For example, to send a request to a server, a client does:

[source,c]
----
Messenger.exhibitStimulus(MsgRequestOut);
----

This unnecessarily exposes the fact that messages are involved; to be
more consistent, that should probably be something like:

[source,c]
----
this.exhibitStimulus();
----

Note that "observations" are hidden on the server side API.  The
programmer is responsible for setting the internal state of the
ServiceProvider (perhaps by reading a sensor instrument), but
`exhibitBehavior` will construct the right outgoing message, which
will be passed as the `ObservationIn` paramater of the client's
`observeBehavior` callback.


